services:
   postgres:
     container_name: postgres-sql-ZenFin
     image: postgres

     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: Venom07%
       GDATA: /var/lib/postgresql/data
       POSTGRES_DB: ZenFIn_DB
     volumes:
       - postgres:/data/postgres
     ports:
      - 5432:5432
     networks:
      - spring-demo
     restart: unless-stopped


networks:
  spring-demo:
    driver: bridge
volumes:
  postgres:
    driver: local