spring:
  mailing:
    frontend:
      activation-url: https://www.ZenFin.com/activate-account
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/ZenFin
    username: postgres
    password: Venom07%
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    username: chethanks340@gmail.com
    password: xhzn sryq osqz aixw
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
    host: smtp.gmail.com
    port: 587
  data:
    redis:
      host: localhost # Replace with your Redis server hostname or IP
      port: 6379      # Default Redis port





application:
  security:
    secreteName: ZenKey
    jwt:
      expiration: 86400000

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1
  port: 8088
  address: 0.0.0.0








#logging:
#  level:
#    org.springframework: DEBUG


