spring:
  mailing:
    frontend:
      activation-url: http://www.ZenFin.com/activate-account
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/ZenFin
    username: postgres
    password: Venom07%
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: chethanks340@gmail.com
    password: zegb cjqw gfbn cpix
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    secreteId: projects/458586569167/secrets/encryption-key/versions/2
    jwt:
      expiration: 8640000

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1
  port: 8088


